[package]
name = "lunest"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

# configuration
toml = { version = "0.8", default-features = false, features = ["parse"] }
walkdir = "2.5"
globset = "0.4"
merge = "0.1"

# bridge
serde_json = "1.0"
notify = "6.1"

# cli
clap = { version = "4.5", features = ["derive"] }
yansi = "1.0"

[build-dependencies]
anyhow = "1.0"
walkdir = "2.5"
