[workspace]
members = [
    ".",
    "./bundler",
]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
walkdir = "2.5"

[package]
name = "lunest"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
globset = "0.4"
merge = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = { version = "0.8", default-features = false, features = ["parse"] }
walkdir.workspace = true
crossterm = { version = "0.28", default-features = false, features = ["windows"] }
similar = "2.6"

[build-dependencies]
bundler = { path = "./bundler" }
anyhow.workspace = true
