[package]
name = "lunest"
version = "0.0.0"
edition = "2021"

[dependencies]
# error handling
anyhow = "1.0"

# configuration
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }
walkdir = "2.5"
globset = "0.4"

# bridge
serde_json = "1.0"
notify = "6.1"

# cli
clap = { version = "4.5", features = ["derive"] }
yansi = "1.0"
