[package]
name = "lunest"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }
serde_json = "1.0"
notify = "6.1"
walkdir = "2.5"
globset = "0.4"
yansi = "1.0"
