[package]
name = "lunest"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = { version = "0.28", default-features = false, features = ["windows"] }
globset = "0.4"
indexmap = "2.7"
lua_cmds = { path = "../lua_cmds" }
merge = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
similar = "2.6"
tempfile = "3.14"
toml = { version = "0.8", default-features = false, features = ["parse"] }
walkdir.workspace = true
which = "7.0"

[build-dependencies]
bundler = { path = "../bundler", features = ["build-script"] }
