[package]
name = "lua_cmds"
version.workspace = true
edition.workspace = true

[features]
default = ["lua51", "lua52", "lua53", "lua54", "luajit"]
lua51 = []
lua52 = []
lua53 = []
lua54 = []
luajit = []
