[package]
name = "luacmds"
version.workspace = true
edition.workspace = true

[features]
default = ["lua54"]
lua51 = []
lua52 = []
lua53 = []
lua54 = []
luajit = []

[dependencies]
zstd = { workspace = true }

[build-dependencies]
zstd = { workspace = true, features = ["zdict_builder"] }
