[package]
name = "luacmds"
version.workspace = true
edition.workspace = true

[dependencies]
zstd = { workspace = true }

[build-dependencies]
zstd = { workspace = true, features = ["zdict_builder"] }
