[package]
name = "lua-rt"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
zstd.workspace = true

[dev-dependencies]
rstest = { version = "0.24", default-features = false }
tempfile.workspace = true

[build-dependencies]
zstd.workspace = true
