name: CI

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: full
  RUST_LOG: trace
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: mlugg/setup-zig@v1

      - name: cargo test
        run: cargo test --workspace --all-targets

      - name: lunest run
        run: cargo run -- run --group all

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: mlugg/setup-zig@v1

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets


  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - uses: mlugg/setup-zig@v1

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: zig fmt
        run: zig fmt --check .

      - name: stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
